## 配置文件中的值，全为默认值

## 启用的 adapter, 内置有 http, ws, reverse-ws, webhook
adapters:
  - http
  - ws

## 是否开启认证流程, 若为 true 则建立连接时需要验证 verifyKey
## 建议公网连接时开启
enableVerify: false
verifyKey: 1234567890

## 开启一些调式信息
debug: false

## 是否开启单 session 模式, 若为 true，则自动创建 session 绑定 console 中登录的 bot
## 开启后，接口中任何 sessionKey 不需要传递参数
## 若 console 中有多个 bot 登录，则行为未定义
## 确保 console 中只有一个 bot 登陆时启用
singleMode: false

## 历史消息的缓存大小
## 同时，也是 http adapter 的消息队列容量
cacheSize: 4096

## adapter 的单独配置，键名与 adapters 项配置相同
adapterSettings:
  ## 详情看 http adapter 使用说明 配置
  http:
    host: localhost
    port: 8080
    cors: ["*"]
    unreadQueueMaxSize: 100

  ## 详情看 websocket adapter 使用说明 配置
  ws:
    host: localhost
    port: 8081
    reservedSyncId: -1
# 可选，心跳服务
#heartbeat:
#  # 可选，是否启用心跳，默认不启用
#  enable: true
#  # 可选，心跳启动延迟，默认1000
#  delay: 1000
#  # 可选，心跳周期，默认15000
#  period: 15000
#  # 必选，心跳PING的地址列表
#  destinations:
#    - https://postman-echo.com/post
#  # 可选，心跳PING时需要带上的请求体
#  extraBody:
#    # 填上你需要的请求体（如QQ等信息）
#    qq: 775150
#  # 可选，心跳PING时需要带上的请求头
#  extraHeaders:
#    # 填上你需要的请求头（如授权信息等）
#    Authorization: basic xxx
